### PR TITLE
Create face recognition with fca and ann algorithm

### PR DESCRIPTION
**Pull request by Akshayakathraji**

### CODE REVIEW

**Comment by Akshayakathraji** [comment]
implementation of pca with ann for facwe recognition

**Comment by Akshayakathraji** [comment]
karan

**Comment by Akshayakathraji** [comment]
face recognition

**Comment by knavachaitanya** [comment]
Hi.Mam u have commented on my repo.i couldn't understand what is the problem ur facing could u please provide the exact problem ur facing.Thanking u for  giving feedback .

**Pull request closed without merging**
